#!/bin/bash

#Setting the system Time
timedatectl set-ntp true

#Partitioning the Drives
#Look the commands up with fdisk -> m
fdisk /dev/sda << EOF
	g
	n
	
	
	+550M
	n
	
	
	
	t	
	1
	1
	w
EOF

#Making the Storage?

mkfs.ext4 /dev/sda1
mkfs.ext4 /dev/sda2

mount /dev/sda2 /mnt


#Downlaoding essentials like linuxkernel, etc.
pacstrap /mnt base linux linux-firmware

genfstab -U /mnt >> /mnt/etc/fstab

chmod a=rwx aAS_exp2_nr
cp aAS_exp2_nr /mnt
#rm aAS_exp2_nr
#rm aAS_exp_nr
cp -r ../linuxsetupsformyuseohmygod /mnt
#rm -r ../linuxsetupsformyuseohmygod

arch-chroot /mnt ./aAS_exp2_nr

systemctl start NetworkManager
systemctl enable NetworkManager

reboot
