#!/bin/bash

#Setting the Timezone
ln -sf /usr/share/zoneinfo/Europe/Berlin /etc/localtime

#Syncing Systemclock?
hwclock --systohc

#Setting the locale
sed -i 's/#en_US.UTF8 UTF8/en_US.UTF8 UTF8;/' /etc/locale.gen
locale-gen

#Warning not to fuck something up from now on
echo -e "####################\n#     IMPORTANT    #\n# FROM NOW ON TYPE #\n#    EVERYTHING    #\n#     PERFECTLY    #\n#IF YOU HAVE A TYPO#\n#YOU HAVE TO REPEAT#\n#    THE COMMAND   #\n#     YOURSELF     #\n####################"

#setting the hostname
#echo --TYPE IN YOUR HOSTNAME--IF YOU DONT CARE JUST TYPE ARCH--

hostname=arch
echo $hostname > /etc/hostname

echo -e "127.0.0.1     localhost\n::1       localhost\n127.0.1.1     $hostname.localdomain     $hostname" > /etc/hosts

unset hostname

#Setting the Users up

echo --TYPE THE PASSWORD FOR THE ROOT--
passwd root

#installing essential Stuff
pacman -S grub efibootmgr networkmanager<< EOF
	y
EOF

#I dont know...
mkdir /boot/EFI
mount /dev/sda1 /boot/EFI
grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck
grub-mkconfig -o /boot/grub/grub.cfg

rm aAS_exp2

systemctl start NetworkManager
systemctl enable NetworkManager

exit

reboot

#echo --THE SETUP IS NOW COMPLETE--YOU CAN NOW DO WHATEVER THE FUCK YOU WANT--