#!/bin/bash

#FOLLOWED THIS TUTORIAL ALONG: https://www.youtube.com/watch?v=PQgyW10xD8s
#MAKE SURE YOU HAVE A VALID INTERNET CONNECTION FOR THIS SETUP TO WORK | TEST WITH "ping google.com"

#FIRST PART OF THE SETUP

#Setting the system Time
timedatectl set-ntp true

#Partitioning the Drives
#Look the commands up with fdisk -> m
fdisk /dev/sda << EOF
	g
	n
	
	
	+550M
	n
	
	
	+2G
	n
	
	
	
	t
	1
	1
	t
	2
	19
	w
EOF

#Making the Storage?

mkfs.fat -F32 /dev/sda1
mkswap /dev/sda2
swapon /dev/sda2
mkfs.ext4 /dev/sda3

mount /dev/sda3 /mnt


#Downlaoding essentials like linuxkernel, etc.
pacstrap /mnt base linux linux-firmware

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt

