#!/bin/bash

#FOLLOW THIS TUTORIAL ALONG: https://www.youtube.com/watch?v=PQgyW10xD8s
#MAKE SURE YOU HAVE A VALID INTERNET CONNECTION FOR THIS SETUP TO WORK | TEST WITH "ping google.com"

#Setting the system Time
timedatectl set-ntp true

#Partitioning the Drives
#Look the commands up with fdisk -> m
fdisk /dev/sda << EOF
	g
	n
	
	
	+550M
	n
	
	
	+2G
	n
	
	
	
	t
	1
	1
	t
	2
	19
	w
EOF

#Making the Storage?

mkfs.fat -F32 /dev/sda1
mkswap /dev/sda2
swapon /dev/sda2
mkfs.ext4 /dev/sda3

mount /dev/sda3 /mnt


#Downlaoding essential like linuxkernel, etc.
pacstrap /mnt base linux linux-firmware

genfstab -U /mnt >> /mnt/etc/fstab

arch-chroot /mnt

#Setting the Timezone
ln -sf /usr/share/zoneinfo/Europe/Berlin/etc/localtime

#Syncing Systemclock?
hwclock --systohc

#Setting the locale and then the wheelgroup to every permission
sed -i 's/#en_US.UTF8 UTF8/en_US.UTF8 UTF8;/' /etc/locale.gen
sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL;/' /etc/locale.gen

#setting the hostname
read hostname
echo $hostname > /etc/hostname

echo -e "127.0.0.1     localhost\n::1       localhost\n127.0.1.1     $hostname.localdomain     $hostname" > /etc/hosts

#Setting the Users up

echo TYPE THE PASSWORD FOR THE ROOT
passwd root

echo TYPE THE NAME OF THE NEW USER
read UserName
useradd -m $UserName
echo TYPE THE PASSWORD OF THE NEW USER
passwd $UserName

#adding the new User to some groups
usermod -aG wheel,audio,video,optical,storage $UserName

unset UserName

#installing essential Stuff
pacman -S sudo grub efibootmgr dosfstools os-prober mtools<< EOF
	y
EOF

#I dont know...
mkdir /boot/EFI
mount /dev/sda1 /boot/EFI
grub-install --target=x86_64-efi --bootloader-id=grub_uefi --recheck
grub-mkconfig -o /boot/grub/grub.cfg

