#!/bin/bash

#MAKE SURE YOU HAVE A VALID INTERNET CONNECTION FOR THIS SETUP TO WORK | TEST WITH "ping google.com"

timedatectl set-ntp true

sed -e 's/\s*\([\+0-9a-zA-Z]*/\l/' << EOF | fdisk ${TGTDEV}
	g
	n
	
	
	+550M
	n
	
	
	+2G
	n
	
	
	
	t
	1
	1
	t
	2
	19
	w
EOF