#!/bin/bash

#Download the java thing and wget
pacman -S jre-openjdk wget<< EOF
	y
EOF

#Make a folder for the minecraft server
mkdir minecraft_Server
#cd into said folder
cd minecraft_Server

#Install the minecraft server.jar for the version 1.18.2
wget https://launcher.mojang.com/v1/objects/c8f83c5655308435b3dcf03c06d9fe8740a77469/server.jar

#Make the "Start.sh" file
echo "--ENTER THE MAXIMUM RAM USAGE FOR THE SERVER IN MEGABYTES--"
read Xmx
echo "--ENTER THE MINIMUM RAM FOR THE SERVER IN MEGABYTES--"
read Xms
echo "--MAKING THE Start.sh FILE--"

echo "java -$XmxM -$XmsM -jar server.jar nogui" >> Start.sh

#Making own Eula file to avoid the Server shutting down
echo "eula=true" >> eula.txt

#Starting the SERVER
./Start.sh

